/* 
 * Maps Booking Partners API
 *
 * # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
namespace IO.Swagger.Model
{
    /// <summary>
    /// OneOfinlineResponse4225Code
    /// </summary>
    public interface OneOfinlineResponse4225Code
    {
    
    }
}
