/* 
 * Maps Booking Partners API
 *
 * # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Выбранное время недоступно для записи
    /// </summary>
    /// <value>Выбранное время недоступно для записи</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum SlotUnavailableError
    {
        /// <summary>
        /// Enum SLOTUNAVAILABLE for value: SLOT_UNAVAILABLE
        /// </summary>
        [EnumMember(Value = "SLOT_UNAVAILABLE")]
        SLOTUNAVAILABLE = 1    }
}
