/* 
 * Maps Booking Partners API
 *
 * # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Обновление записи запрещено. Например, в организации запрещён перенос записей позже, чем за 1 час до назначенного визита.
    /// </summary>
    /// <value>Обновление записи запрещено. Например, в организации запрещён перенос записей позже, чем за 1 час до назначенного визита.</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum UpdateForbiddenError
    {
        /// <summary>
        /// Enum UPDATEFORBIDDEN for value: UPDATE_FORBIDDEN
        /// </summary>
        [EnumMember(Value = "UPDATE_FORBIDDEN")]
        UPDATEFORBIDDEN = 1    }
}
