/* 
 * Maps Booking Partners API
 *
 * # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Appointment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AppointmentTests
    {
        // TODO uncomment below to declare an instance variable for Appointment
        //private Appointment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Appointment
            //instance = new Appointment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Appointment
        /// </summary>
        [Test]
        public void AppointmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Appointment
            //Assert.IsInstanceOfType<Appointment> (instance, "variable 'instance' is a Appointment");
        }


        /// <summary>
        /// Test the property 'ServiceIds'
        /// </summary>
        [Test]
        public void ServiceIdsTest()
        {
            // TODO unit test for the property 'ServiceIds'
        }
        /// <summary>
        /// Test the property 'ResourceId'
        /// </summary>
        [Test]
        public void ResourceIdTest()
        {
            // TODO unit test for the property 'ResourceId'
        }
        /// <summary>
        /// Test the property 'Datetime'
        /// </summary>
        [Test]
        public void DatetimeTest()
        {
            // TODO unit test for the property 'Datetime'
        }

    }

}
