/* 
 * Maps Booking Partners API
 *
 * # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BookingInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BookingInputTests
    {
        // TODO uncomment below to declare an instance variable for BookingInput
        //private BookingInput instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BookingInput
            //instance = new BookingInput();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BookingInput
        /// </summary>
        [Test]
        public void BookingInputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BookingInput
            //Assert.IsInstanceOfType<BookingInput> (instance, "variable 'instance' is a BookingInput");
        }


        /// <summary>
        /// Test the property 'CompanyId'
        /// </summary>
        [Test]
        public void CompanyIdTest()
        {
            // TODO unit test for the property 'CompanyId'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Test]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Test]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }
        /// <summary>
        /// Test the property 'Appointment'
        /// </summary>
        [Test]
        public void AppointmentTest()
        {
            // TODO unit test for the property 'Appointment'
        }
        /// <summary>
        /// Test the property 'PrebookingId'
        /// </summary>
        [Test]
        public void PrebookingIdTest()
        {
            // TODO unit test for the property 'PrebookingId'
        }

    }

}
