/* 
 * Maps Booking Partners API
 *
 * # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Booking
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BookingTests
    {
        // TODO uncomment below to declare an instance variable for Booking
        //private Booking instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Booking
            //instance = new Booking();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Booking
        /// </summary>
        [Test]
        public void BookingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Booking
            //Assert.IsInstanceOfType<Booking> (instance, "variable 'instance' is a Booking");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'ServiceIds'
        /// </summary>
        [Test]
        public void ServiceIdsTest()
        {
            // TODO unit test for the property 'ServiceIds'
        }
        /// <summary>
        /// Test the property 'ResourceId'
        /// </summary>
        [Test]
        public void ResourceIdTest()
        {
            // TODO unit test for the property 'ResourceId'
        }
        /// <summary>
        /// Test the property 'Datetime'
        /// </summary>
        [Test]
        public void DatetimeTest()
        {
            // TODO unit test for the property 'Datetime'
        }

    }

}
