/* 
 * Maps Booking Partners API
 *
 * # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BookingUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BookingUpdateTests
    {
        // TODO uncomment below to declare an instance variable for BookingUpdate
        //private BookingUpdate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BookingUpdate
            //instance = new BookingUpdate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BookingUpdate
        /// </summary>
        [Test]
        public void BookingUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BookingUpdate
            //Assert.IsInstanceOfType<BookingUpdate> (instance, "variable 'instance' is a BookingUpdate");
        }


        /// <summary>
        /// Test the property 'CompanyId'
        /// </summary>
        [Test]
        public void CompanyIdTest()
        {
            // TODO unit test for the property 'CompanyId'
        }
        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Test]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }
        /// <summary>
        /// Test the property 'Datetime'
        /// </summary>
        [Test]
        public void DatetimeTest()
        {
            // TODO unit test for the property 'Datetime'
        }

    }

}
