/* 
 * Maps Booking Partners API
 *
 * # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BookingsBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BookingsBodyTests
    {
        // TODO uncomment below to declare an instance variable for BookingsBody
        //private BookingsBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BookingsBody
            //instance = new BookingsBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BookingsBody
        /// </summary>
        [Test]
        public void BookingsBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BookingsBody
            //Assert.IsInstanceOfType<BookingsBody> (instance, "variable 'instance' is a BookingsBody");
        }


        /// <summary>
        /// Test the property 'Booking'
        /// </summary>
        [Test]
        public void BookingTest()
        {
            // TODO unit test for the property 'Booking'
        }

    }

}
