/* 
 * Maps Booking Partners API
 *
 * # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FeedCompany
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FeedCompanyTests
    {
        // TODO uncomment below to declare an instance variable for FeedCompany
        //private FeedCompany instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FeedCompany
            //instance = new FeedCompany();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FeedCompany
        /// </summary>
        [Test]
        public void FeedCompanyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FeedCompany
            //Assert.IsInstanceOfType<FeedCompany> (instance, "variable 'instance' is a FeedCompany");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Coordinates'
        /// </summary>
        [Test]
        public void CoordinatesTest()
        {
            // TODO unit test for the property 'Coordinates'
        }
        /// <summary>
        /// Test the property 'Photos'
        /// </summary>
        [Test]
        public void PhotosTest()
        {
            // TODO unit test for the property 'Photos'
        }
        /// <summary>
        /// Test the property 'Phones'
        /// </summary>
        [Test]
        public void PhonesTest()
        {
            // TODO unit test for the property 'Phones'
        }
        /// <summary>
        /// Test the property 'Urls'
        /// </summary>
        [Test]
        public void UrlsTest()
        {
            // TODO unit test for the property 'Urls'
        }
        /// <summary>
        /// Test the property 'BookingUrl'
        /// </summary>
        [Test]
        public void BookingUrlTest()
        {
            // TODO unit test for the property 'BookingUrl'
        }
        /// <summary>
        /// Test the property 'Services'
        /// </summary>
        [Test]
        public void ServicesTest()
        {
            // TODO unit test for the property 'Services'
        }
        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Test]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }
        /// <summary>
        /// Test the property 'Rubrics'
        /// </summary>
        [Test]
        public void RubricsTest()
        {
            // TODO unit test for the property 'Rubrics'
        }

    }

}
