/* 
 * Maps Booking Partners API
 *
 * # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FeedCompanyCoordinates
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FeedCompanyCoordinatesTests
    {
        // TODO uncomment below to declare an instance variable for FeedCompanyCoordinates
        //private FeedCompanyCoordinates instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FeedCompanyCoordinates
            //instance = new FeedCompanyCoordinates();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FeedCompanyCoordinates
        /// </summary>
        [Test]
        public void FeedCompanyCoordinatesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FeedCompanyCoordinates
            //Assert.IsInstanceOfType<FeedCompanyCoordinates> (instance, "variable 'instance' is a FeedCompanyCoordinates");
        }


        /// <summary>
        /// Test the property 'Lat'
        /// </summary>
        [Test]
        public void LatTest()
        {
            // TODO unit test for the property 'Lat'
        }
        /// <summary>
        /// Test the property 'Lon'
        /// </summary>
        [Test]
        public void LonTest()
        {
            // TODO unit test for the property 'Lon'
        }

    }

}
