/* 
 * Maps Booking Partners API
 *
 * # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LocalizedText
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LocalizedTextTests
    {
        // TODO uncomment below to declare an instance variable for LocalizedText
        //private LocalizedText instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LocalizedText
            //instance = new LocalizedText();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LocalizedText
        /// </summary>
        [Test]
        public void LocalizedTextInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LocalizedText
            //Assert.IsInstanceOfType<LocalizedText> (instance, "variable 'instance' is a LocalizedText");
        }


        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property '_LocalizedText'
        /// </summary>
        [Test]
        public void _LocalizedTextTest()
        {
            // TODO unit test for the property '_LocalizedText'
        }

    }

}
