/* 
 * Maps Booking Partners API
 *
 * # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OneOfResourceInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OneOfResourceInformationTests
    {
        // TODO uncomment below to declare an instance variable for OneOfResourceInformation
        //private OneOfResourceInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OneOfResourceInformation
            //instance = new OneOfResourceInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OneOfResourceInformation
        /// </summary>
        [Test]
        public void OneOfResourceInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OneOfResourceInformation
            //Assert.IsInstanceOfType<OneOfResourceInformation> (instance, "variable 'instance' is a OneOfResourceInformation");
        }



    }

}
