/* 
 * Maps Booking Partners API
 *
 * # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OneOfinlineResponse4224Code
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OneOfinlineResponse4224CodeTests
    {
        // TODO uncomment below to declare an instance variable for OneOfinlineResponse4224Code
        //private OneOfinlineResponse4224Code instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OneOfinlineResponse4224Code
            //instance = new OneOfinlineResponse4224Code();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OneOfinlineResponse4224Code
        /// </summary>
        [Test]
        public void OneOfinlineResponse4224CodeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OneOfinlineResponse4224Code
            //Assert.IsInstanceOfType<OneOfinlineResponse4224Code> (instance, "variable 'instance' is a OneOfinlineResponse4224Code");
        }



    }

}
