/* 
 * Maps Booking Partners API
 *
 * # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OneOfinlineResponse422Code
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OneOfinlineResponse422CodeTests
    {
        // TODO uncomment below to declare an instance variable for OneOfinlineResponse422Code
        //private OneOfinlineResponse422Code instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OneOfinlineResponse422Code
            //instance = new OneOfinlineResponse422Code();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OneOfinlineResponse422Code
        /// </summary>
        [Test]
        public void OneOfinlineResponse422CodeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OneOfinlineResponse422Code
            //Assert.IsInstanceOfType<OneOfinlineResponse422Code> (instance, "variable 'instance' is a OneOfinlineResponse422Code");
        }



    }

}
