/* 
 * Maps Booking Partners API
 *
 * # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ServiceNotFoundError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ServiceNotFoundErrorTests
    {
        // TODO uncomment below to declare an instance variable for ServiceNotFoundError
        //private ServiceNotFoundError instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ServiceNotFoundError
            //instance = new ServiceNotFoundError();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ServiceNotFoundError
        /// </summary>
        [Test]
        public void ServiceNotFoundErrorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ServiceNotFoundError
            //Assert.IsInstanceOfType<ServiceNotFoundError> (instance, "variable 'instance' is a ServiceNotFoundError");
        }



    }

}
