/* 
 * Maps Booking Partners API
 *
 * # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ServiceResources
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ServiceResourcesTests
    {
        // TODO uncomment below to declare an instance variable for ServiceResources
        //private ServiceResources instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ServiceResources
            //instance = new ServiceResources();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ServiceResources
        /// </summary>
        [Test]
        public void ServiceResourcesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ServiceResources
            //Assert.IsInstanceOfType<ServiceResources> (instance, "variable 'instance' is a ServiceResources");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DurationSeconds'
        /// </summary>
        [Test]
        public void DurationSecondsTest()
        {
            // TODO unit test for the property 'DurationSeconds'
        }

    }

}
