/* 
 * Maps Booking Partners API
 *
 * # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UpdateForbiddenError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateForbiddenErrorTests
    {
        // TODO uncomment below to declare an instance variable for UpdateForbiddenError
        //private UpdateForbiddenError instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateForbiddenError
            //instance = new UpdateForbiddenError();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateForbiddenError
        /// </summary>
        [Test]
        public void UpdateForbiddenErrorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateForbiddenError
            //Assert.IsInstanceOfType<UpdateForbiddenError> (instance, "variable 'instance' is a UpdateForbiddenError");
        }



    }

}
